### ISSUE TITLE
never see any transition to WeChat

### ISSUE THREAD

**Issue by anuragm1969** [aaronbruckner/wechatAndroidLoginDemo#1]
Please help im trying to login with wechat but never got any transition to wechat app.

I m using following code. 

api = WXAPIFactory.createWXAPI(activity, Constants.WE_CHAT_APP_ID, true)
        api!!.registerApp(Constants.WE_CHAT_APP_ID)
        val req = SendAuth.Req()
        req.scope = "snsapi_userinfo"
        req.state = "none"
        api!!.sendReq(req)

I have changed wechat signature in developer console after the successful app review. Hope this is fine.
mainfest entry:

     <activity
            android:name=".wxapi.WXEntryActivity"
            android:exported="true"
            android:label="@string/app_name"
            android:launchMode="singleTop">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:scheme="sdksample" />
            </intent-filter>
        </activity>

**Comment by aaronbruckner** [comment]
Hey anuragm1969, I don't officially support this repo. It was just a major pain to figure out Android WeChat so I figured I'd throw up the code I eventually figured out in github. There was many different things that could mess up WeChat (so many that it was kinda just a blur as I was working through it trying to make **any** progress).

My only advice is to just continually review what you have and go over every single step looking for anything that doesn't look right. It's been so long sense I've had to touch this that this repo is really the only helpful resource remaining.

Unfortunately, WeChat just tends to fail with no details as to why unless everything is perfectly configured..

Good luck!
